version: '3.8'

services:
  nacos:
    image: nacos/nacos-server:v2.3.2
    container_name: micro-nacos-standalone-derby
    ports:
      - '8080:8080'
      - '8848:8848'
      - '9848:9848'
    environment:
      MODE: standalone
      NACOS_AUTH_TOKEN: jiJsjXz1cQK4rR8d7kiziu+HKqfE/fMblZ26Rlvbwyw=
      NACOS_AUTH_IDENTITY_KEY: micro-nacos-standalone-derby
      NACOS_AUTH_IDENTITY_VALUE: micro-nacos-standalone-derby
    volumes:
      - /Users/HHX/workspace/docker/micro-nacos-standalone-derby:/home/nacos/data
